import socket
import time

def push_config_to_asr9000(config, host="localhost", port=2222):
    try:
        with socket.create_connection((host, port), timeout=5) as s:
            try:
                s.recv(1024)  # Read initial prompt
            except Exception as e:
                print(f"Error receiving initial prompt: {e}")
                return
            for line in config.splitlines():
                try:
                    s.sendall(line.encode() + b"\n")
                    resp = s.recv(1024)
                    print(resp.decode())
                except (ConnectionAbortedError, ConnectionResetError) as ce:
                    print("Connection closed by device during config push.")
                    break
                except Exception as e:
                    print(f"Socket error during config push: {e}")
                    break
            try:
                s.sendall(b"exit\n")
                resp = s.recv(1024)
                print(resp.decode())
            except (ConnectionAbortedError, ConnectionResetError):
                print("Connection closed by device after exit.")
            except Exception as e:
                print(f"Socket error after exit: {e}")
    except Exception as e:
        print(f"Socket connection error: {e}")

def test_push_cisco_asr9000():
    # Example config as generated by your system
    config = """interface GigabitEthernet0/1\n  ip address 172.16.0.1 255.255.255.0\n  description 'WAN Edge'\n  no shutdown\nexit"""
    print("Pushing config to simulated Cisco ASR 9000...")
    push_config_to_asr9000(config)
    print("Push complete.")
