name: Push Config to SBI

on:
  push:
    paths:
      - 'configs/**'
      - '.github/workflows/sbi_push.yml'

jobs:
  push-to-sbi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: SBI Push (Simulated CLI)
        run: |
          python ci_push_to_sbi.py configs/cisco_asr_9000_config_latest.txt
